package View;

import Model.Pemain;

/**
 *
 * @author Ahmad
 */
public class HomePage extends javax.swing.JFrame {
    public HomePage() {
        initComponents();
        this.setTitle("Beranda");
        
        lbl_SelamatDatang.setText("Selamat datang, " + Pemain.getNamaAkun() + "!");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_PapanPeringkat = new javax.swing.JButton();
        btn_Main = new javax.swing.JButton();
        btn_KeluarAkun = new javax.swing.JButton();
        lbl_SelamatDatang = new javax.swing.JLabel();
        lbl_SelamatDatang1 = new javax.swing.JLabel();
        lbl_SelamatDatang2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_PapanPeringkat.setBackground(new java.awt.Color(0, 102, 255));
        btn_PapanPeringkat.setForeground(new java.awt.Color(255, 255, 255));
        btn_PapanPeringkat.setText("Papan Peringkat");
        btn_PapanPeringkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PapanPeringkatActionPerformed(evt);
            }
        });

        btn_Main.setBackground(new java.awt.Color(0, 102, 255));
        btn_Main.setForeground(new java.awt.Color(255, 255, 255));
        btn_Main.setText("Main");
        btn_Main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MainActionPerformed(evt);
            }
        });

        btn_KeluarAkun.setBackground(new java.awt.Color(0, 102, 255));
        btn_KeluarAkun.setForeground(new java.awt.Color(255, 255, 255));
        btn_KeluarAkun.setText("Keluar Akun");
        btn_KeluarAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KeluarAkunActionPerformed(evt);
            }
        });

        lbl_SelamatDatang.setBackground(new java.awt.Color(0, 102, 255));
        lbl_SelamatDatang.setFont(new java.awt.Font("Candara", 1, 28)); // NOI18N
        lbl_SelamatDatang.setForeground(new java.awt.Color(0, 102, 255));
        lbl_SelamatDatang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_SelamatDatang.setText("Selamat datang, <Akun>");

        lbl_SelamatDatang1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lbl_SelamatDatang1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_SelamatDatang1.setText("Uji kemapuanmu dengan menjawab pertanyaan dalam game ini,");

        lbl_SelamatDatang2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lbl_SelamatDatang2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_SelamatDatang2.setText("dan lengkapi pengetahuanmu!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btn_PapanPeringkat, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_KeluarAkun, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(69, 69, 69))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_SelamatDatang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SelamatDatang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_SelamatDatang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lbl_SelamatDatang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_SelamatDatang1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_SelamatDatang2)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_KeluarAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_PapanPeringkat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MainActionPerformed
        new PlayPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_MainActionPerformed

    private void btn_PapanPeringkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PapanPeringkatActionPerformed
        new LeaderboardPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_PapanPeringkatActionPerformed

    private void btn_KeluarAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KeluarAkunActionPerformed
        Pemain.setNamaAkun("");
        Pemain.setKataSandi("");
        Pemain.setJurusan("");
        Pemain.setUniversitas("");
        Pemain.setTotalMain(0);
        Pemain.setNilaiAkhir(0);
        
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_KeluarAkunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_KeluarAkun;
    private javax.swing.JButton btn_Main;
    private javax.swing.JButton btn_PapanPeringkat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_SelamatDatang;
    private javax.swing.JLabel lbl_SelamatDatang1;
    private javax.swing.JLabel lbl_SelamatDatang2;
    // End of variables declaration//GEN-END:variables
}
