package View;

import Helper.Koneksi;
import Model.Pemain;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmad
 */
public class LoginPage extends javax.swing.JFrame {

    public LoginPage() {
        initComponents();
        this.setTitle("Masuk ke akun");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_NamaAkun = new javax.swing.JTextField();
        btn_Masuk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_AkunBaru = new javax.swing.JLabel();
        txt_KataSandi = new javax.swing.JPasswordField();
        lbl_notifikasi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(600, 400));

        txt_NamaAkun.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_NamaAkun.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NamaAkun.setToolTipText("Username");
        txt_NamaAkun.setBorder(null);
        txt_NamaAkun.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txt_NamaAkun.setMinimumSize(new java.awt.Dimension(200, 35));
        txt_NamaAkun.setPreferredSize(new java.awt.Dimension(200, 35));

        btn_Masuk.setBackground(new java.awt.Color(0, 102, 255));
        btn_Masuk.setForeground(new java.awt.Color(255, 255, 255));
        btn_Masuk.setText("Masuk");
        btn_Masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MasukActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KUSKUL");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nama Akun");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Kata Sandi");

        lbl_AkunBaru.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_AkunBaru.setForeground(new java.awt.Color(0, 102, 255));
        lbl_AkunBaru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_AkunBaru.setText("Buat akun baru");
        lbl_AkunBaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_AkunBaruMouseClicked(evt);
            }
        });

        txt_KataSandi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_KataSandi.setToolTipText("Password");
        txt_KataSandi.setBorder(null);

        lbl_notifikasi.setForeground(new java.awt.Color(255, 0, 0));
        lbl_notifikasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(177, 177, 177)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lbl_notifikasi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(51, 51, 51)
                        .add(lbl_AkunBaru, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, btn_Masuk, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, txt_NamaAkun, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, txt_KataSandi))
                .add(173, 173, 173))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(53, 53, 53)
                .add(jLabel1)
                .add(28, 28, 28)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txt_NamaAkun, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txt_KataSandi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btn_Masuk, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(13, 13, 13)
                .add(lbl_AkunBaru)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(lbl_notifikasi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        txt_NamaAkun.getAccessibleContext().setAccessibleName("");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MasukActionPerformed
        try {
            java.sql.Connection conn = (java.sql.Connection) Koneksi.GetConnection();
            java.sql.Statement statement = conn.createStatement();
            java.sql.ResultSet result = statement.executeQuery("SELECT * FROM tbakun WHERE NamaAkun='" +txt_NamaAkun.getText() + "'");
            
            if(result.next()) {
                if(txt_KataSandi.getText().equals(result.getString("KataSandi"))){

                    Pemain.setNamaAkun(result.getString("NamaAkun"));
                    Pemain.setJurusan(result.getString("Jurusan"));
                    Pemain.setUniversitas(result.getString("Universitas"));
                    Pemain.setTotalMain(result.getInt("TotalMain"));
                    Pemain.setNilaiAkhir(result.getInt("NilaiAkhir"));
                    
                    new HomePage().setVisible(true);
                    lbl_notifikasi.setText("Selamat bermain, " + Pemain.getNamaAkun());
                    this.dispose();
                }
                else {
                    lbl_notifikasi.setText("Kata sandi yang Anda masukkan salah");
                    txt_KataSandi.setText("");
                    txt_KataSandi.requestFocus();
                }
            }
            else {
                lbl_notifikasi.setText("Nama akun/Kata sandi tidak benar");
            }
        }
        catch(SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(rootPane, "Login Gagal " + ex);
        }
    }//GEN-LAST:event_btn_MasukActionPerformed

    private void lbl_AkunBaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AkunBaruMouseClicked
        new RegistrationPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_AkunBaruMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Masuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_AkunBaru;
    private javax.swing.JLabel lbl_notifikasi;
    private javax.swing.JPasswordField txt_KataSandi;
    private javax.swing.JTextField txt_NamaAkun;
    // End of variables declaration//GEN-END:variables
}
